export const CURRENCIES = [
  { code: 'CDF', name: 'Franc Congolais', symbol: 'CDF' },
  { code: 'USD', name: 'Dollar US', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'Livre Sterling', symbol: '£' },
  { code: 'JPY', name: 'Yen Japonais', symbol: '¥' },
  { code: 'CAD', name: 'Dollar Canadien', symbol: 'C$' },
  { code: 'AUD', name: 'Dollar Australien', symbol: 'A$' },
  { code: 'CHF', name: 'Franc Suisse', symbol: 'CHF' },
  { code: 'CNY', name: 'Yuan Chinois', symbol: '¥' },
  { code: 'INR', name: 'Roupie Indienne', symbol: '₹' },
  { code: 'BRL', name: 'Real Brésilien', symbol: 'R$' },
  { code: 'MXN', name: 'Peso Mexicain', symbol: '$' },
  { code: 'SGD', name: 'Dollar de Singapour', symbol: 'S$' },
  { code: 'HKD', name: 'Dollar de Hong Kong', symbol: 'HK$' },
  { code: 'NOK', name: 'Couronne Norvégienne', symbol: 'kr' },
  { code: 'SEK', name: 'Couronne Suédoise', symbol: 'kr' },
  { code: 'DKK', name: 'Couronne Danoise', symbol: 'kr' },
  { code: 'PLN', name: 'Zloty Polonais', symbol: 'zł' },
  { code: 'TRY', name: 'Livre Turque', symbol: '₺' },
  { code: 'RUB', name: 'Rouble Russe', symbol: '₽' },
  { code: 'ZAR', name: 'Rand Sud-Africain', symbol: 'R' },
  { code: 'KRW', name: 'Won Sud-Coréen', symbol: '₩' },
  { code: 'THB', name: 'Baht Thaïlandais', symbol: '฿' },
  { code: 'MYR', name: 'Ringgit Malaisien', symbol: 'RM' },
  { code: 'IDR', name: 'Roupie Indonésienne', symbol: 'Rp' },
  { code: 'PHP', name: 'Peso Philippin', symbol: '₱' },
  { code: 'VND', name: 'Dong Vietnamien', symbol: '₫' },
  { code: 'EGP', name: 'Livre Égyptienne', symbol: 'E£' },
  { code: 'NGN', name: 'Naira Nigérian', symbol: '₦' },
  { code: 'KES', name: 'Shilling Kenyan', symbol: 'KSh' },
  { code: 'GHS', name: 'Cedi Ghanéen', symbol: 'GH₵' },
  { code: 'UGX', name: 'Shilling Ougandais', symbol: 'USh' },
  { code: 'TZS', name: 'Shilling Tanzanien', symbol: 'TSh' },
  { code: 'ZMW', name: 'Kwacha Zambien', symbol: 'ZK' },
  { code: 'BWP', name: 'Pula Botswanéen', symbol: 'P' },
  { code: 'NAD', name: 'Dollar Namibien', symbol: 'N$' },
  { code: 'MUR', name: 'Roupie Mauricienne', symbol: '₨' },
  { code: 'SCR', name: 'Roupie Seychelloise', symbol: '₨' },
  { code: 'MAD', name: 'Dirham Marocain', symbol: 'MAD' },
  { code: 'TND', name: 'Dinar Tunisien', symbol: 'TND' },
  { code: 'DZD', name: 'Dinar Algérien', symbol: 'DZD' },
  { code: 'LYD', name: 'Dinar Libyen', symbol: 'LYD' },
  { code: 'SDG', name: 'Livre Soudanaise', symbol: 'SDG' },
  { code: 'ETB', name: 'Birr Éthiopien', symbol: 'ETB' },
  { code: 'SOS', name: 'Shilling Somalien', symbol: 'SOS' },
  { code: 'DJF', name: 'Franc Djiboutien', symbol: 'DJF' },
  { code: 'KMF', name: 'Franc Comorien', symbol: 'KMF' },
  { code: 'BIF', name: 'Franc Burundais', symbol: 'BIF' },
  { code: 'RWF', name: 'Franc Rwandais', symbol: 'RWF' },
  { code: 'XAF', name: 'Franc CFA (BEAC)', symbol: 'FCFA' },
  { code: 'XOF', name: 'Franc CFA (BCEAO)', symbol: 'CFA' },
  { code: 'XPF', name: 'Franc CFP', symbol: 'CFP' },
  { code: 'ANG', name: 'Florin des Antilles Néerlandaises', symbol: 'ƒ' },
  { code: 'AWG', name: 'Florin d\'Aruba', symbol: 'ƒ' },
  { code: 'BBD', name: 'Dollar de la Barbade', symbol: 'Bds$' },
  { code: 'BMD', name: 'Dollar des Bermudes', symbol: 'BD$' },
  { code: 'BND', name: 'Dollar de Brunei', symbol: 'B$' },
  { code: 'BSD', name: 'Dollar des Bahamas', symbol: 'B$' },
  { code: 'FJD', name: 'Dollar Fidjien', symbol: 'FJ$' },
  { code: 'GYD', name: 'Dollar Guyanais', symbol: 'G$' },
  { code: 'JMD', name: 'Dollar Jamaïcain', symbol: 'J$' },
  { code: 'KYD', name: 'Dollar des Îles Caïmans', symbol: 'CI$' },
  { code: 'LRD', name: 'Dollar Libérien', symbol: 'L$' },
  { code: 'NZD', name: 'Dollar Néo-Zélandais', symbol: 'NZ$' },
  { code: 'SBD', name: 'Dollar des Îles Salomon', symbol: 'SI$' },
  { code: 'SRD', name: 'Dollar du Suriname', symbol: 'SRD' },
  { code: 'TTD', name: 'Dollar de Trinité-et-Tobago', symbol: 'TT$' },
  { code: 'TWD', name: 'Dollar de Taïwan', symbol: 'NT$' },
  { code: 'XCD', name: 'Dollar des Caraïbes orientales', symbol: 'EC$' },
] as const;

export type CurrencyCode = typeof CURRENCIES[number]['code'];

export const getCurrencyByCode = (code: string) => {
  return CURRENCIES.find(currency => currency.code === code) || CURRENCIES[0];
};

export const getDefaultCurrency = () => CURRENCIES[0]; // CDF 