// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzgbnnamdmqdknpzjzmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6Z2JubmFtZG1xZGtucHpqem1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTMwMDAsImV4cCI6MjA2MzMyOTAwMH0.Eze9MbCe9nVlmjI1XzIdMbOhWH3yhutvsn3PC-fcVeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);